### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. 

### ISSUE THREAD

**Issue by gerrytan** [daime/docker-statsd-console#1]
Got this error when running `make`:
```
➜  docker-statsd-console git:(master) make
Error response from daemon: No such container: docker-statsd-console
make: [stop] Error 1 (ignored)
Sending build context to Docker daemon  58.88kB
Step 1/7 : FROM mhart/alpine-node
latest: Pulling from mhart/alpine-node
bdf0201b3a05: Already exists
753bb570cf34: Pull complete
Digest: sha256:3da2e59e992b303b0ba9ee9542ef8cf72be11f3dbebfae2ffea3428fcb6711fd
Status: Downloaded newer image for mhart/alpine-node:latest
 ---> 468d19895ec5
Step 2/7 : RUN apk add --update git
 ---> Running in 5ab13dd3eda4
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20190108-r0)
(2/7) Installing nghttp2-libs (1.35.1-r0)
(3/7) Installing libssh2 (1.8.2-r0)
(4/7) Installing libcurl (7.64.0-r1)
(5/7) Installing expat (2.2.6-r0)
(6/7) Installing pcre2 (10.32-r1)
(7/7) Installing git (2.20.1-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 22 MiB in 23 packages
Removing intermediate container 5ab13dd3eda4
 ---> 4d348a18bf7b
Step 3/7 : RUN git clone https://github.com/etsy/statsd.git /opt/statsd &&        cd /opt/statsd &&        git checkout v0.7.2
 ---> Running in 2a1153c1e22a
Cloning into '/opt/statsd'...
Note: checking out 'v0.7.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 972993e lib/helpers: added support for null 'ms' metrics.
Removing intermediate container 2a1153c1e22a
 ---> 330b60fa73c4
Step 4/7 : COPY ./config.js /opt/statsd/
 ---> f50420b888ad
Step 5/7 : EXPOSE 8125/udp
 ---> Running in 2b22c18644de
Removing intermediate container 2b22c18644de
 ---> 0e18d40f5b1d
Step 6/7 : EXPOSE 8126
 ---> Running in 183fdbe9d5e7
Removing intermediate container 183fdbe9d5e7
 ---> 9714106cfb86
Step 7/7 : CMD ["/usr/bin/node", "/opt/statsd/stats.js", "/opt/statsd/config.js"]
 ---> Running in a4c728492178
Removing intermediate container a4c728492178
 ---> 8318aa782f13
Successfully built 8318aa782f13
Successfully tagged daime/docker-statsd-console:latest
util.js:146
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:146:11)
    at Object.<anonymous> (/opt/statsd/lib/config.js:31:6)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/opt/statsd/stats.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
make: [run] Error 1 (ignored)
```

**Comment by mwconceicao** [comment]
@gerrytan thanks for reporting. A fix (#2) was merged and this issue should be solved.
